name: polutionheatmap
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5

  cloud_firestore: ^0.13.7



  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
         - asset: fonts/SourceSansPro-Regular.ttf